### ISSUE TITLE
'Manage Your Subscription' shows twice. 

### ISSUE THREAD

**Issue by manishsuwal** [raamdev/wp-comment-subscriptions#10]
![screen shot 2014-01-16 at 11 06 42 am](https://f.cloud.github.com/assets/5318719/1927941/a01e7da6-7e6e-11e3-89ef-4ae7c0b5a3c4.png)
@raamdev

**Comment by raamdev** [comment]
@manishsuwal This was a bug in the Independent Publisher theme, which has been fixed.

Please note: Development of WP Comment Subscriptions has been halted. Please switch to Subscribe to Comments Reloaded, which I am now maintaining. See also: https://github.com/raamdev/wp-comment-subscriptions#note-development-halted
