### ISSUE TITLE
Typo in polish translations

### ISSUE THREAD

**Issue by pawel-tomkiel** [raamdev/wp-comment-subscriptions#11]
"Poprosiłeś o możliwość zarządzanai swoimi subskrypcjami" should be "Poprosiłeś o możliwość zarządzania swoimi subskrypcjami" :)

**Comment by raamdev** [comment]
@neonkowy Thanks for the report! Are you currently using this plugin? I'm no longer maintaining WP Comment Subscriptions and instead I'm now working on Comment Mail, which is a lot better:

- https://wordpress.org/plugins/comment-mail/
- https://github.com/websharks/comment-mail/
