### ISSUE TITLE
Move 'Notifications' a bit Higher on Independent Publisher

### ISSUE THREAD

**Issue by manishsuwal** [raamdev/wp-comment-subscriptions#9]
![screen shot 2014-01-12 at 10 39 53 am](https://f.cloud.github.com/assets/5318719/1895651/c1f6f1e6-7b4a-11e3-9a37-8b7817a591af.png)
![screen shot 2014-01-12 at 11 14 43 am](https://f.cloud.github.com/assets/5318719/1895652/c7c8020e-7b4a-11e3-83c8-f632d6f9420c.png)

**Comment by raamdev** [comment]
@manishsuwal Please see: [How do I make the Subscribe to Comments Reloaded Advanced Options look better?](https://github.com/raamdev/independent-publisher#how-do-i-make-the-subscribe-to-comments-reloaded-advanced-options-look-better)

Please note: Development of WP Comment Subscriptions has been halted. Please switch to Subscribe to Comments Reloaded, which I am now maintaining. See also: https://github.com/raamdev/wp-comment-subscriptions#note-development-halted
